# Development environment values
# Usage: helm upgrade frontend ./frontend -f values.yaml -f values-dev.yaml

replicaCount: 1

autoscaling:
  enabled: false

# MFE allowed origins for development
mfe:
  allowedOrigins: "localhost 127.0.0.1 *.dev.abc.com *.dev.partner1.com"

# Relaxed resources for dev
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
