apiVersion: v2
name: mono-repo
description: Umbrella chart for BFF + Frontend monorepo
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: bff
    version: "1.0.0"
    repository: "file://../charts/bff"
    condition: bff.enabled

  - name: frontend
    version: "1.0.0"
    repository: "file://../charts/frontend"
    alias: web-cl
    condition: web-cl.enabled

  - name: frontend
    version: "1.0.0"
    repository: "file://../charts/frontend"
    alias: web-hs
    condition: web-hs.enabled

  - name: mfe
    version: "1.0.0"
    repository: "file://../charts/mfe"
    alias: mfe-summary
    condition: mfe-summary.enabled

  - name: mfe
    version: "1.0.0"
    repository: "file://../charts/mfe"
    alias: mfe-profile
    condition: mfe-profile.enabled
